# Generated by Django 4.2.7 on 2023-11-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officesharingapi', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
